sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - realpath

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - . ./build.sh
  - . ./dist.do
